name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.0
  flutter_html: ^3.0.0-beta.2 # Suggested upgrade as per error message
  win32: ^5.4.0
  chewie: ^1.5.0 # Downgraded to avoid conflict
  cupertino_icons: ^1.0.8
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

